version: '3.8'

services: 
    db:
        container_name: ${CONTAINER_NAME}
        image: postgres:${POSTGRES_VERSION}
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432

volumes: 
    dbdata:
